[dosbox]
memsize = 64

[sdl]
output = opengl
fullresolution = original
autolock = true

[render]
aspect = true
scaler = normal2x

[cpu]
core = dynamic
cputype = 486
cycles = 97240

[serial]
serial1=file file:serial.log multiplier:12

[autoexec]
@echo off
mount c: /home/nuclear/dos
mount d: .
d:
set PATH=%PATH%;c:\bin;C:\NC;C:\prog\nasm;C:\prog\vim\vim72;C:\windows
set TEMP=c:\windows\temp
echo For dev env setup: watdev, bcdev, djdev, tpdev, owdev
